# Generated by Django 5.2.7 on 2025-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=20, verbose_name='День недели')),
                ('lesson_number', models.PositiveIntegerField(verbose_name='Номер урока')),
                ('class_name', models.CharField(max_length=20, verbose_name='Класс')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=255, verbose_name='Учитель')),
                ('classroom', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Расписание уроков',
                'ordering': ['day_of_week', 'lesson_number'],
            },
        ),
    ]
