# Generated by Django 5.2.7 on 2025-12-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
