# Generated by Django 5.2.7 on 2025-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('replaced_teacher', models.CharField(max_length=255, verbose_name='ФИО учителя, которого замещают')),
                ('lesson_number', models.CharField(max_length=10, verbose_name='Номер урока')),
                ('class_name', models.CharField(max_length=20, verbose_name='Класс')),
                ('substitute_teacher', models.CharField(max_length=255, verbose_name='ФИО замещающего учителя')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('classroom', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Замена',
                'verbose_name_plural': 'Замены',
                'ordering': ['date', 'lesson_number'],
            },
        ),
    ]
