# Generated by Django 5.2.7 on 2025-10-23 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО ученика')),
                ('student_class', models.CharField(max_length=50, verbose_name='Класс')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='awards_photos/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date', 'student_name'],
            },
        ),
    ]
