# Generated by Django 5.2.7 on 2025-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='resaulted',
            field=models.BooleanField(default=False),
        ),
    ]
