# Generated by Django 5.2.7 on 2025-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_award_resaulted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='resaulted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат'),
        ),
    ]
